### PR TITLE
Q4 23.4 external release 

### PR DESCRIPTION
**Pull request by praveennish**
Cassandra, Spark, Kafka and MongoDB workload

### CODE REVIEW

**Comment by angus0wang** [comment]
It`s good for TPCDS-Spark

**Comment by HaitaoLi2Intel** [comment]
It looks good for Cassandra.

**Comment by mrw7** [comment]
It looks good for Mongo-ycsb.

**Comment by yyxxll12345** [comment]
It looks good for Kafka.

**Review by ywu75 — APPROVED** [review]

**Pull request merged**
